hash_func: allow Configure -Dhash_func=name
define new Config symbol hash_func, handle it in Configure
and store it on config.h
Move old -Accflags=-DPERL_HASH_FUNC_* from ccflags to config.h

Allow abbrevations MURMUR64 for MURMUR_HASH_64 and OOAT for ONE_AT_A_TIME

diff --git a/Configure b/Configure
--- a/Configure
+++ b/Configure
@@ -261,6 +261,7 @@ flex=''
 gmake=''
 grep=''
 gzip=''
+hash_func=''
 inews=''
 ksh=''
 less=''
@@ -20609,7 +20610,7 @@ esac
 
 case "$i_db" in
 define)
-	: Check the return type needed for hash
+	: Check the return type needed for bdb hash
 	echo " "
 	echo "Checking return type needed for hash for Berkeley DB ..." >&4
 	$cat >try.c <<EOCP
@@ -23533,6 +23534,38 @@ case "$d_vfork" in
 	;;
 esac
 
+: see which hash_func to use. can be left empty
+case "$ccflags" in
+    *-DPERL_HASH_FUNC_[A-Z]*)
+        ans=`echo $ccflags|$sed -r 's/.*-DPERL_HASH_FUNC_([A-Z0-9_]+).*/\1/'`
+        ccflags=`echo $ccflags|$sed -r 's/-DPERL_HASH_FUNC_([A-Z0-9_]+)//'`
+	echo "Moving PERL_HASH_FUNC_$ans from ccflags to config.h" >&4
+        ;;
+    *)  $echo " "
+        $echo "Perl will select the best hash function for you automatically."
+        $echo "Available hash functions: FNV1A SIPHASH SUPERFAST DJB2 SDBM"
+        $echo "  OAAT OAAT_HARD OAAT_OLD ONE_AT_A_TIME_HARD ONE_AT_A_TIME ONE_AT_A_TIME_OLD"
+        $echo "  MURMUR3 MURMUR64A MURMUR64B MURMUR_HASH_64A MURMUR_HASH_64B CRC32 METRO64CRC METRO64"
+        rp="Which hash function do you want to use?"
+        dflt=default
+        . ./myread
+esac
+ans=`echo $ans|tr a-z A-Z`
+case "$ans" in
+    DEFAULT)
+        hash_func='' ;;
+    OAAT|OAAT_HARD|OAAT_OLD)
+        hash_func=`echo $ans|sed 's,OAAT,ONE_AT_A_TIME,'` ;;
+    MURMUR64A|MURMUR64B)
+        hash_func=`echo $ans|sed 's,MURMUR64,MURMUR_HASH_64,'` ;;
+    FNV1A|SIPHASH|SUPERFAST|MURMUR3|DJB2|SDBM|ONE_AT_A_TIME_HARD|ONE_AT_A_TIME|ONE_AT_A_TIME_OLD|MURMUR_HASH_64A|MURMUR_HASH_64B|CRC32|METRO64CRC|METRO64)
+        hash_func=$ans ;;
+    [0-9A-Z_]*)
+        echo >&2 "$me:  Fatal Error: Invalid hash_func name '$ans'";
+        $rm -rf UU
+        exit 1 ;;
+esac
+
 : Check extensions
 echo " "
 echo "Looking for extensions..." >&4
@@ -24726,6 +24759,7 @@ groupstype='$groupstype'
 gzip='$gzip'
 h_fcntl='$h_fcntl'
 h_sysfile='$h_sysfile'
+hash_func='$hash_func'
 hint='$hint'
 hostcat='$hostcat'
 hostgenerate='$hostgenerate'
